# Generated by Django 3.2.4 on 2021-06-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
